# 配置端口号，默认就是8080
# 也可以在启动时指定：java -jar -Dserver.port=8080 e_configure.jar 或 java -jar e_configure.jar --server.port=8080
server:
  port: 8080
# 配置应用的根路径。默认是 /，区别于springboot1（server.context-path），springboot2多了servlet节点
  servlet:
    context-path: /e_configure

# Spring Boot使用LogBack作为日志实现，apache Commons Logging作为日志接口
logging:
# 日志级别，设置到包/类
  level:
    pers.hdh.e_configure: warn
  file: my.log
  path: ./logs/
# 控制格式，注意yml文件不能以 % 开头，解决：使用单引号括起来
# Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token found character '%' that cannot start any token
  pattern:
    console: '%date{HH:mm:ss} %level %logger{20}.%M %L :%m%n'
    file: '%date{ISO8601} %level [%thread] %logger{20}.%M %L :%m%n'

author:
  name: hdonghong

encrypt:
  enable: true
